# spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: customer-service
#              uri: lb://customer-service
#              predicates:
#                - Path=/customer,/customer/**
#              filters:
#                - RewritePath=^/customer(?<remaining>/?.*), /api/customers$\{remaining}
#
#            - id: ebank-service
#              uri: lb://ebank-service
#              predicates:
#                - Path=/ebank,/ebank/**
#              filters:
#                - RewritePath=^/ebank(?<remaining>/?.*), /api/accounts$\{remaining}
