spring.application.name=ebank-bot
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=qwen/qwen3.8-27b
spring.ai.openai.chat.options.reasoning-effort=none
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8066

spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8082
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8083