spring.application.name=ebank-service
server.port=8083

spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true
spring.cloud.openfeign.circuitbreaker.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:h2:mem:ebank-db
spring.h2.console.enabled=true

spring.ai.mcp.server.protocol=streamable